{
  try {
    testSame("a[f()] *= 2;");
    fail("Should raise an exception");
  }
 catch (  RuntimeException e) {
  }
}
