{
  if (Throwable_initCause != null) {
    Object[] args={cause};
    try {
      Throwable_initCause.invoke(ex,args);
    }
 catch (    Exception e) {
    }
  }
  return ex;
}
