{
  try {
    testSame("++a[f()];");
    fail("Should raise an exception");
  }
 catch (  RuntimeException e) {
  }
}
