{
  try {
    testSame("for (;x++;) {}");
    fail("Should raise an exception");
  }
 catch (  RuntimeException e) {
  }
}
